sudo: false
language: python
python:
  - "2.7"
before_install:
  - pip install -r requirements.txt 
  - pip install -r requirements-dev.txt 
  - cp config.py.template config.py
script: nosetests test
after_success:
  - pip install coveralls
  - coveralls
